change did to wallet address
cvoxelprotocol/vess pull request #23
Opened 2023-06-18 21:52 UTC by Rashmi-278

Summary
- Display wallet address instead of DID
- Enable copying of wallet address

2023-06-20 09:54 UTC, KoukiMinamoto commented
test comment

2023-06-20 09:55 UTC, kitakaze-kan commented
@Rashmi-278
you can use below property to get wallet address!
import { getAddressFromPkh } from 'vess-sdk'
const address = getAddressFromPkh(did)

2023-06-20 09:56 UTC, kitakaze-kan requested changes

2023-06-24 10:22 UTC, kitakaze-kan approved these changes
LGFM! thanks!

2023-06-24 10:22 UTC, merged