Add NavigationDrawer Component and link to SYNAPSS
cvoxelprotocol/vess pull request #27
Opened 2023-07-05 05:01 UTC by KoukiMinamoto

I created NavigationDrawer on mobile and profileRate Banner on profile page.
But, since profileRate banner is still WIP so I commented it out for now.

<img width="1014" alt="スクリーンショット 2023-07-05 13 59 52" src="https://github.com/cvoxelprotocol/vess/assets/51091911/5da500a5-9998-431a-aabc-a2a217218f21">
<img width="359" alt="スクリーンショット 2023-07-05 14 01 12" src="https://github.com/cvoxelprotocol/vess/assets/51091911/77fb4ac5-d5c3-4f9e-8d95-95794b8d3733">

2023-07-05 14:36 UTC, kitakaze-kan requested changes

2023-07-05 14:36 UTC, kitakaze-kan commented on src/components/organism/Modal/Onboarding/PFOnboardingForm.tsx
> +import styled from '@emotion/styled'
Can you please stop committing these WIP changes? A large number of unrelated commits will make future reviews difficult...

2023-07-05 14:36 UTC, kitakaze-kan commented on package.json
> +    "react-icons": "^4.9.0",
where do you use it?

2023-07-08 09:48 UTC, KoukiMinamoto commented
I recreated a pull request here.
#28

2023-08-01 10:42 UTC, kitakaze-kan commented
can we delete this branch? @KoukiMinamoto

2023-08-07 01:56 UTC, closed without merging