Feature/og
cvoxelprotocol/vess pull request #51
Opened 2024-05-18 14:21 UTC by KoukiMinamoto

- Add OG Image
- Add Share API
- Add Empty state of AvatarEdit

2024-05-19 01:55 UTC, kitakaze-kan requested changes

2024-05-19 01:55 UTC, kitakaze-kan commented on src/components/app/NavigationList.tsx
> +          {connection === 'connected' && (
他のユーザーを見た時などに、ログインしてない場合にアカウント作成の導線が消えてしまっているので、ログインしてない時にはTOPページ(ログインページ)に飛ばす導線があった方が良さそうです。
<img width="791" alt="スクリーンショット 2024-05-19 10 42 40" src="https://github.com/cvoxelprotocol/vess/assets/46702100/a7142ddd-3c95-4df8-93c3-2f7ee4c4d771">

2024-05-19 02:01 UTC, kitakaze-kan requested changes

2024-05-19 02:01 UTC, kitakaze-kan commented on src/pages/[vessid]/index.tsx
> +  const title = props.user?.name || props.user?.vessId || 'Profile'
ここ、OG見て名前で検索するとか考えるとvessIdが優先度高い方が良いかなと思うのですがどうでしょう？(user.nameは表示に使ってるだけなので)

2024-05-19 04:35 UTC, KoukiMinamoto commented on src/components/app/NavigationList.tsx
> +          {connection === 'connected' && (
ありがとうございます！
[対応]
ログインボタンをナビゲーションリストに配置する

2024-05-19 04:36 UTC, KoukiMinamoto commented on src/components/avatar/AvatarEditModal.tsx
> +          '/default_profile.jpg',
ありがとうございます！
対応します！デフォルト画像もアップデートします！

2024-05-19 04:36 UTC, KoukiMinamoto commented on src/components/profile/ProfileContainer.tsx
> +                    id={xLink.displayLink || `${xLink.url.replace(X_URL, '')}`}
ありがとうございます！
これは完璧にミスです！元に戻します。

2024-05-19 04:38 UTC, KoukiMinamoto commented on src/pages/[vessid]/index.tsx
> +  const title = props.user?.name || props.user?.vessId || 'Profile'
ありがとうございます！
これも、いろいろ試してみてたのを戻すの忘れてました。
OGに表示するIDはvessIDがいいですね。ページのタイトルはnameにしようかなと考えてます(Twitterに倣って)

2024-05-19 07:12 UTC, KoukiMinamoto commented on src/pages/[vessid]/index.tsx
> +  const title = props.user?.name || props.user?.vessId || 'Profile'
すみません、コメントされてる箇所見間違えてました！

ページのタイトルを、VESS IDよりユーザー名を優先しているのは意図してです。
IDは一意ですが、一般的なユーザーはIDでユーザーを判別してる人は少ない(覚えにくい)のでPCのタブとかでページタイトルを確認する際はユーザー名の方にしたいです。(Twitter / LinkedInなどはこの仕様)
OG画像にはIDを記載しているのでIDはそちらで確認する感じでもいいかと思います！

他の代替案として、「ユーザー名(VESS ID)」の形もありです。(インスタはこの仕様)

それと、IDを記載する際TwitterやInstaは「＠」があるのでそれがIDなのかユーザー名なのか判断できるようになってるので、IDを優先する場合でも少なくともそれに値するマークやprefix / sufixを決めたいです！

2024-05-19 07:44 UTC, kitakaze-kan commented on src/pages/[vessid]/index.tsx
> +  const title = props.user?.name || props.user?.vessId || 'Profile'
あ、私もタイトルはどっちでも良いです。
> OG画像にはIDを記載しているのでIDはそちらで確認する感じでもいいかと思います！

私が気にしてるのはこちらです！現在はtitleをそのままOGに使ってるのでtitleとのところにコメントしています。
OG画像の認識が同じであれば、
> const imageUrl = `${process.env.NEXT_PUBLIC_VESS_URL}/api/og/avatar?title=${title}&avatar=${avatar}`

ここのtitleの変数を、${props.user?.vessId | props.user?.name | props.user?.did } などに変更してもらえると良いかと思います。
またIDにprefix付けるのであれば、@で良いかなと思います！(社会的に共通認識取れてますし) もしsurfixであれば 「.id」「.vid」とかですかね？

2024-05-20 02:26 UTC, KoukiMinamoto commented on src/pages/[vessid]/index.tsx
> +  const title = props.user?.name || props.user?.vessId || 'Profile'
遅くなってすみません！コメントの意図を汲み取れておらず、申し訳ないです🙇‍♂️

[Page title]
Name -> VESS ID -> Wallet Address(DID) -> "プロフィール"
[OG Title]
VESS ID -> Name -> Wallet Address(DID) -> "VESS" 

の優先度で表示させるようにしました！
また取り急ぎ、IDの方は @ つけるようにしています。

確認お願いします！

2024-05-20 03:07 UTC, kitakaze-kan approved these changes
LGTM

2024-05-20 05:18 UTC, merged