Feature/obv3
cvoxelprotocol/vess pull request #64
Opened 2024-10-05 08:28 UTC by KoukiMinamoto

VESS webへのオープンバッジ対応

2024-10-06 02:58 UTC, kitakaze-kan requested changes

2024-10-06 02:58 UTC, kitakaze-kan commented on src/components/credentialDetail/CredentialDetailContainer.tsx
> +            {credential?.vc.credentialSubject?.achievement?.criteria?.narrative && (
分岐がとても増えて見づらくなってしまうので、下記のような形はいかがでしょうか？

```ts

const achievement = useMemo(() => {
    if (!credential) return null
    return credential.vc.credentialSubject.achievement &&
      credential?.credentialType?.name === 'openbadge'
      ? credential.vc.credentialSubject.achievement
      : null
  }, [credential])
  
{achievement && {
<>
{achievement.criteria?.narrative && (...)}
{achievement.criteria?.achievementType && (...)}
...
</>
}

```

2024-10-06 03:57 UTC, kitakaze-kan reviewed
コメントしたところ以外はLGTMです！

2024-10-06 05:50 UTC, kitakaze-kan requested changes

2024-10-06 05:50 UTC, kitakaze-kan commented on src/components/credentialDetail/CredentialDetailContainer.tsx
> +                  達成条件
オープンバッジ種類？

2024-10-06 05:50 UTC, kitakaze-kan commented on src/components/credentialDetail/CredentialDetailContainer.tsx
> +            {credential?.vc.credentialSubject?.achievement?.achievementType && (
credential?.vc.credentialSubject?.achievement?.types  && credential?.vc.credentialSubject?.achievement?.types.length>0

2024-10-06 05:50 UTC, kitakaze-kan commented on src/components/credentialDetail/CredentialDetailContainer.tsx
> +                  {credential?.vc.credentialSubject?.achievement?.achievementType}
credential?.vc.credentialSubject?.achievement?.types.join(",")とかが良いかもしれません

2024-10-06 06:43 UTC, KoukiMinamoto commented on src/components/credentialDetail/CredentialDetailContainer.tsx
> +            {credential?.vc.credentialSubject?.achievement?.achievementType && (
achevement.typeとは別に、achievementTypeというプロパティが任意で存在していて、それを指しています！（ややこしい)
https://www.imsglobal.org/spec/ob/v3p0#achievement
<img width="813" alt="Screenshot 2024-10-06 at 15 43 14" src="https://github.com/user-attachments/assets/06f694c1-60a9-4964-b300-f70aefa19881">

2024-10-06 07:39 UTC, kitakaze-kan commented on src/components/credentialDetail/CredentialDetailContainer.tsx
> +            {credential?.vc.credentialSubject?.achievement?.achievementType && (
<img width="1015" alt="スクリーンショット 2024-10-06 16 38 35" src="https://github.com/user-attachments/assets/c011ff74-4390-475d-9f26-efd09a30c5d7">
https://github.com/cvoxelprotocol/vess-kit/pull/6/commits/ec293ed53f4568caa5319a43922184c9f8571784#diff-eba40d21298b65ef79a41492f0877b6d93799eb8e15bea0885336550df422b95L189
このコミットでachievementType消えてますがこれが間違いですかね、、？

2024-10-06 07:59 UTC, KoukiMinamoto commented on src/components/credentialDetail/CredentialDetailContainer.tsx
> +            {credential?.vc.credentialSubject?.achievement?.achievementType && (
[https://github.com/cvoxelprotocol/vess-kit/commit/9d3e1af3c99668ffd360f82ec47c7e31967b1ad7#diff-eba40d21298b65ef79a41492f0877b6d93799eb8e15bea0885336550df422b95R171](https://github.com/cvoxelprotocol/vess-kit/commit/9d3e1af3c99668ffd360f82ec47c7e31967b1ad7#diff-eba40d21298b65ef79a41492f0877b6d93799eb8e15bea0885336550df422b95R171)
わかりづらくてすみません、こちらのコミットでachievementTypeをoptionalに対応させるためにif文の方に移動しているのでこれで大丈夫かと思います！
<img width="604" alt="Screenshot 2024-10-06 at 16 54 27" src="https://github.com/user-attachments/assets/dca4f035-2930-4913-88d4-84bae7ba9505">

2024-10-06 08:51 UTC, KoukiMinamoto commented on src/components/credentialDetail/CredentialDetailContainer.tsx
> +            {credential?.vc.credentialSubject?.achievement?.achievementType && (
すみません、発行のところでachievementTypeに対応はしてたのですが、そもそもDBのスキーマに加えるのを忘れていました。。。
再度DBのマイグレーション等の実装コミットしたので確認お願いいたします🙇‍♂️

2024-10-10 00:00 UTC, kitakaze-kan approved these changes
LGTM

2024-10-10 08:11 UTC, merged